# Generated by Django 6.0.3 on 2026-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='waste_uploads/')),
                ('rule_key', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('recyclable', 'Recyclable'), ('organic', 'Organic'), ('hazardous', 'Hazardous'), ('unclear', 'Unclear')], default='uncertain', max_length=20)),
                ('waste_bin', models.CharField(choices=[('black', 'Black'), ('green', 'Green'), ('blue', 'Blue'), ('specialist', 'Specialist'), ('gray', 'Gray')], default='gray', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
