# Generated by Django 6.0.3 on 2026-03-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteitem',
            name='category',
            field=models.CharField(choices=[('recyclable', 'Recyclable'), ('organic', 'Organic'), ('hazardous', 'Hazardous'), ('unclear', 'Unclear'), ('multiple_items', 'Multiple Items')], default='uncertain', max_length=20),
        ),
        migrations.AlterField(
            model_name='wasteitem',
            name='waste_bin',
            field=models.CharField(choices=[('black', 'Black'), ('green', 'Green'), ('blue', 'Blue'), ('specialist', 'Specialist'), ('gray', 'Gray'), ('multiple', 'Multiple')], default='gray', max_length=20),
        ),
    ]
