# Generated by Django 6.0.3 on 2026-03-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_wasteitem_category_alter_wasteitem_waste_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteitem',
            name='suggestions',
            field=models.CharField(null=True),
        ),
    ]
