# Generated by Django 6.0.3 on 2026-03-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_wasteitem_id'),
        ('api', '0003_wasteitem_suggestions'),
    ]

    operations = [
    ]
