# Generated by Django 5.2.12 on 2026-03-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20260319_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteitem',
            name='category',
            field=models.CharField(choices=[('recyclable', 'Recyclable'), ('organic', 'Organic'), ('hazardous', 'Hazardous'), ('unclear', 'Unclear'), ('multiple_items', 'Multiple Items')], default='unclear', max_length=20),
        ),
        migrations.AlterField(
            model_name='wasteitem',
            name='suggestions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
