# Generated by Django 6.0.3 on 2026-03-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_wasteitem_category_alter_wasteitem_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteitem',
            name='suggestions',
        ),
        migrations.AlterField(
            model_name='wasteitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
