# Generated by Django 6.0.3 on 2026-03-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_wasteitem_suggestions_alter_wasteitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteitem',
            name='suggestions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wasteitem',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='waste_uploads'),
        ),
    ]
